stages:
  - test
  - build

test:
  stage: test
  image: golang:1.17
  script: 
   - go test .

static-analysis:
 stage: test
 image:
  name: sonarsource/sonar-scanner-cli
  entrypoint: [""]
 variables:
 script:
  - sonar-scanner -Dsonar.projectKey=ci-test1 -Dsonar.sources=. -Dsonar.host.url=http://192.168.7.249:9000 -Dsonar.login=sqp_53abf74e200fdcc755dc994254b93050ddbbc6bf

build:
  stage: build
  image: docker:latest
  script:
   - docker build .